Refactored fmt output to loginfo output
Spruik/libre-common pull request #33
Opened 2021-09-09 06:31 UTC by mattyzzy

Some of the other comment line is remained for now because I need to discuss some more thing with Geoff about how to implement disconnect in auto paho. They will be resolved as soon as the new version is implemented.

2021-09-09 12:50 UTC, tomhollingworth requested changes
Hey @mattyzzy I was a bit lazy in the previous review and didn't properly check the context of the logging. Can we use s.logWarn / s.logError where appropriate. Happy for you to make your own judgement on which type of logger to use

2021-09-09 12:50 UTC, tomhollingworth commented on common/drivers/edgeConnectorMQTT.go
> +		OnConnectError: func(err error) { s.LogInfo("error whilst attempting connection: %s\n", err) },
Maybe s.LogError is better given the context. Sorry I should of taken a closer look at the time.

2021-09-09 12:50 UTC, tomhollingworth commented on common/drivers/edgeConnectorMQTT.go
> +			OnClientError: func(err error) { s.LogInfo("server requested disconnect: %s\n", err) },
Maybe s.LogError is better given the context. Sorry I should of taken a closer look at the time.

2021-09-09 12:50 UTC, tomhollingworth commented on common/drivers/libreConnectorMQTT.go
> +		OnConnectError: func(err error) { s.LogInfo("error whilst attempting connection: %s\n", err) },
Maybe s.LogError is better given the context. Sorry I should of taken a closer look at the time.

2021-09-09 12:50 UTC, tomhollingworth commented on common/drivers/libreConnectorMQTT.go
> +			OnClientError: func(err error) { s.LogInfo("server requested disconnect: %s\n", err) },
Maybe s.LogError is better given the context. Sorry I should of taken a closer look at the time.

2021-09-09 12:50 UTC, tomhollingworth commented on common/drivers/plcConnectorMQTT.go
> +		OnConnectError: func(err error) { s.LogInfo("error whilst attempting connection: %s\n", err) },
Maybe s.LogError is better given the context. Sorry I should of taken a closer look at the time.

2021-09-09 12:50 UTC, tomhollingworth commented on common/drivers/plcConnectorMQTT.go
> +			OnClientError: func(err error) { s.LogInfo("server requested disconnect: %s\n", err) },
Maybe s.LogError is better given the context. Sorry I should of taken a closer look at the time.

2021-09-09 12:50 UTC, tomhollingworth commented on common/drivers/plcConnectorMQTT.go
> +					s.LogInfo("server requested disconnect: %s\n", d.Properties.ReasonString)
Maybe s.LogWarn is better given the context. Sorry I should of taken a closer look at the time.

2021-09-09 12:50 UTC, tomhollingworth commented on common/drivers/plcConnectorMQTT.go
> +					s.LogInfo("server requested disconnect; reason code: %d\n", d.ReasonCode)
Maybe s.LogWarn is better given the context. Sorry I should of taken a closer look at the time.

2021-09-09 12:50 UTC, tomhollingworth commented on common/drivers/edgeConnectorMQTT.go
> +					s.LogInfo("server requested disconnect: %s\n", d.Properties.ReasonString)
Maybe s.LogWarn is better given the context. Sorry I should of taken a closer look at the time.

2021-09-09 12:50 UTC, tomhollingworth commented on common/drivers/edgeConnectorMQTT.go
> +					s.LogInfo("server requested disconnect; reason code: %d\n", d.ReasonCode)
Maybe s.LogWarn is better given the context. Sorry I should of taken a closer look at the time.

2021-09-09 12:50 UTC, tomhollingworth commented on common/drivers/pubSubConnectorMQTT.go
> +					s.LogInfo("server requested disconnect; reason code: %d\n", d.ReasonCode)
Maybe s.LogWarn is better given the context. Sorry I should of taken a closer look at the time.

2021-09-09 12:50 UTC, tomhollingworth commented on common/drivers/pubSubConnectorMQTT.go
> +					s.LogInfo("server requested disconnect: %s\n", d.Properties.ReasonString)
Maybe s.LogWarn is better given the context. Sorry I should of taken a closer look at the time.

2021-09-09 12:50 UTC, tomhollingworth commented on common/drivers/pubSubConnectorMQTT.go
> +			OnClientError: func(err error) { s.LogInfo("server requested disconnect: %s\n", err) },
Maybe s.LogError is better given the context. Sorry I should of taken a closer look at the time.

2021-09-09 12:50 UTC, tomhollingworth commented on common/drivers/pubSubConnectorMQTT.go
> +		OnConnectError: func(err error) { s.LogInfo("error whilst attempting connection: %s\n", err) },
Maybe s.LogError is better given the context. Sorry I should of taken a closer look at the time.

2021-09-09 12:55 UTC, mattyzzy commented on common/drivers/edgeConnectorMQTT.go
> +		OnConnectError: func(err error) { s.LogInfo("error whilst attempting connection: %s\n", err) },
Hi @tomhollingworth I had a few seconds of hesitation when I reaad your comment as well but using different loggers absolutely makes more sense to me! Thanks for letting me know! I'll make these changes tomorrow.

2021-09-10 01:22 UTC, tomhollingworth approved these changes
Awesome, thanks @mattyzzy

2021-09-10 01:23 UTC, merged